#!/usr/bin/env bash
# -*- shell-script -*-

# shellcheck source=lib/utils.sh
source "$(dirname "$(dirname "$(dirname "$0")")")/lib/utils.sh"

asdf_which_command() {
  local tool="${1-}"

  if [ -z "$tool" ]; then
    asdf_echo_error "usage: asdf which <command>"
    return 1
  fi

  IFS=' ' read -r plugin full_version <<<"$(asdf_shim_select_version "$tool" 2>/dev/null)"

  if [ -z "$full_version" ]; then
    asdf_echo_error "no command: $tool. Perhaps you have to asdf reshim?"
    return 1
  fi

  asdf_plugin_inside_env "$plugin" "$full_version" asdf_which_command_inside_env "$tool"
}

asdf_which_command_inside_env() {
  local shim_name path executable
  shim_name="$1"

  path="$(asdf_exec_path_inside_env "$shim_name")"
  executable="$(PATH="$path" asdf_which_executable_inside_env "$shim_name")"

  local plugin_name="${plugin_name-}"
  local full_version="${full_version-}"

  if [ -z "$executable" ]; then
    asdf_echo_error "No ${shim_name} executable found for ${plugin_name} ${full_version}"
    return 1
  fi

  echo "$executable"
}


asdf_which_command "$@"
